<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE libro [
  <!ELEMENT libro (titulo, autor, ano, editorial)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT autor (nombre, apellido)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT ano (#PCDATA)>
  <!ELEMENT editorial (#PCDATA)>
  <!ATTLIST libro id CDATA #REQUIRED>
  <!ATTLIST libro idioma CDATA #REQUIRED>
  <!ATTLIST precio moneda CDATA #REQUIRED>
  <!ATTLIST precio valor CDATA #REQUIRED>
]>

<libro id="175" idioma="espaÃ±ol">
  <titulo>el cazador</titulo>
  <autor>
    <nombre>gabriel</nombre>
    <apellido>garcia marques</apellido>
  </autor>
  <ano>1995</ano>
  <editorial>norma</editorial>
  <precio moneda="peso" valor="25000">
</libro>
