=== andrespena9010/XML/alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" type="alumno" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>   

  

  <xs:complexType name="alumno">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="direccion" type="direccion" minOccurs="1" maxOccurs="2"/>
      <xs:element name="telefono" type="xs:integer" minOccurs="0" maxOccurs="5"/>
    </xs:sequence>
    <xs:attribute name="dni" type="dni" />
  </xs:complexType>

  <xs:complexType name="direccion">
    <xs:sequence>
      <xs:element name="calle" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="numero" type="numero" minOccurs="1" maxOccurs="1"/>
      <xs:element name="ciudad" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="provincia" type="provincia" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  
  <xs:simpleType name="dni">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
  

  <xs:simpleType name="numero">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="500"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="provincia">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Badajoz"/>
      <xs:enumeration value="CÃ¡ceres"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== andrespena9010/XML/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>

<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/andrespena9010/XML/raw/main/alumnos.xsd">
 <alumno dni="11771111A">
    <nombre>Juan Andrés</nombre>
    <direccion>
      <calle>Avenida de la Fuente</calle>
      <numero>6</numero>
      <ciudad>Zafra</ciudad>
      <provincia>Badajoz</provincia>
    </direccion>
    <telefono>924555555</telefono>
  </alumno>
  <alumno dni="11772211C">
    <nombre>Jose Sanchez</nombre>
    <direccion>
      <calle>Calle Ancha</calle>
      <numero>3</numero>
      <ciudad>Zafra</ciudad>
      <provincia>Badajoz</provincia>
    </direccion>
    <direccion>
      <calle>Calle Mayor</calle>
      <numero>33</numero>
      <ciudad>Zafra</ciudad>
      <provincia>Badajoz</provincia>
    </direccion>
    <telefono>924550000</telefono>
  </alumno>
</alumnos>
