=== andrespena9010/XML/DTD_1.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT liga1 (partido)*>
<!ELEMENT partido (equipoLocal, equipoVisitante)>
<!ELEMENT equipoLocal (nombre, goles)>
<!ELEMENT equipoVisitante (nombre, goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>

=== andrespena9010/XML/Liga_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE liga1 SYSTEM "https://raw.githubusercontent.com/andrespena9010/XML/main/DTD_1.dtd">

<liga1>
    <partido>
        <equipoLocal>
            <nombre>Nottingham Presa</nombre>
            <goles>0</goles>
        </equipoLocal>
        <equipoVisitante>
            <nombre>Inter de Mitente</nombre>
            <goles>1</goles>
        </equipoVisitante>
    </partido>
    <partido>
        <equipoLocal>
            <nombre>Vodka Juniors</nombre>
            <goles>3</goles>
        </equipoLocal>
        <equipoVisitante>
            <nombre>Sparta da Risa</nombre>
            <goles>3</goles>
        </equipoVisitante>
    </partido>
    <partido>
        <equipoLocal>
            <nombre>Water de MÃºnich</nombre>
            <goles>4</goles>
        </equipoLocal>
        <equipoVisitante>
            <nombre>Esteaua es del grifo</nombre>
            <goles>2</goles>
        </equipoVisitante>
    </partido>
</liga1>
