=== andrespena9010/XML/especies.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="especies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="especie" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="nombre-cientifico" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="familia" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="distribucion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="zona" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="identificador" type="xs:integer" use="required"/>
                        <xs:attribute name="estado" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="extinto"/>
                                    <xs:enumeration value="amenazado"/>
                                    <xs:enumeration value="sin-peligro"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                    <xs:unique name="ID">
                        <xs:selector xpath="especie"/>
                        <xs:field xpath="@identificador"></xs:field>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== andrespena9010/XML/especies.xml
<?xml version="1.0" encoding="UTF-8"?>

<especies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/andrespena9010/XML/refs/heads/xsd/especies.xsd">
    <especie identificador="1" estado="amenazado">
      <nombre nombre-cientifico="Monachus monachus">Foca monje</nombre>
      <familia>Phocidae</familia>
      <distribucion>
        <zona>Costa Atlántica</zona>
        <zona>Costa Mediterránea</zona>
      </distribucion>
    </especie>
    <especie identificador="2" estado="extinto">
      <nombre nombre-cientifico="Panthera onca">Jaguar</nombre>
      <familia>Felidae</familia>
      <distribucion>
        <zona>América Central</zona>
        <zona>América del Sur</zona>
      </distribucion>
    </especie>
    <especie identificador="3" estado="sin-peligro">
      <nombre nombre-cientifico="Chelonia mydas">Tortuga verde</nombre>
      <familia>Cheloniidae</familia>
      <distribucion>
        <zona>Océano Atlántico</zona>
        <zona>Océano Pacífico</zona>
      </distribucion>
    </especie>
  </especies>
