=== andrespena9010/XML/receta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="ingredientes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingrediente" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="cantidad" type="xs:integer" use="optional"/>
                        <xs:attribute name="unidad" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="elaboracion" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="raciones" type="xs:integer" use="required"/>
            <xs:attribute name="dificultad" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== andrespena9010/XML/receta.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/andrespena9010/XML/refs/heads/main/receta.xsd"
    raciones="6" dificultad="media">
    <nombre>Tortilla</nombre>
	<ingredientes>
		<ingrediente cantidad="1" unidad="kilogramo">Patata</ingrediente>
		<ingrediente cantidad="8" unidad="unidades">Huevo</ingrediente>
		<ingrediente cantidad="1" unidad="unidades">Cebolla</ingrediente>
		<ingrediente>Aceite de oliva</ingrediente>
		<ingrediente>Sal</ingrediente>
	</ingredientes>
	<elaboracion>Se pelan las patatas...</elaboracion>
</receta>
