=== andrespena9010/XML/temperatura.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="temperatura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="provincia" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="fecha" type="xs:date" minOccurs="1" maxOccurs="1"/>
                <xs:element name="temperatura_minima" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:double">
                            <xs:minInclusive value="-50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="temperatura_maxima" minOccurs="1" maxOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:double">
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="incidencias" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="incidencia" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="nombre">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="frio"/>
                                                <xs:enumeration value="nieve"/>
                                                <xs:enumeration value="lluvia"/>
                                                <xs:enumeration value="calor"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="severidad">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="alta"/>
                                                <xs:enumeration value="media"/>
                                                <xs:enumeration value="baja"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== andrespena9010/XML/temperatura.xml
<?xml version="1.0" encoding="UTF-8"?>

<temperatura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/andrespena9010/XML/refs/heads/xsd/temperatura.xsd">

	<provincia>Zamora</provincia>
	<fecha>2022-01-07</fecha>
	<temperatura_minima>-5</temperatura_minima>
	<temperatura_maxima>4</temperatura_maxima>
	<incidencias>
		<incidencia nombre="frio" severidad="alta"/>
		<incidencia nombre="nieve" severidad="alta"/>
		<incidencia nombre="lluvia" severidad="media"/>
	</incidencias>
</temperatura>
